export enum CupName {
  MUSHROOM = "mushroom",
  FLOWER = "flower",
  STAR = "star",
  SPECIAL = "special",
  EGG = "egg",
  CROSSING = "crossing",
  SHELL = "shell",
  BANANA = "banana",
  LEAF = "leaf",
  LIGHTNING = "lightning",
  TRIFORCE = "triforce",
  BELL = "bell",
  GOLDEN_DASH = "goldenDash",
  LUCKY_CAT = "luckyCat",
  TURNIP = "turnip",
  PROPELLER = "propeller",
  ROCK = "rock",
  MOON = "moon",
  FRUIT = "fruit",
  BOOMERANG = "boomerang",
  FEATHER = "feather",
  CHERRY = "cherry",
  ACORN = "acorn",
  SPINY = "spiny",
}
