export enum GliderName {
  SUPER_GLIDER = "superGlider",
  CLOUD_GLIDER = "cloudGlider",
  WARIO_WING = "warioWing",
  WADDLE_WING = "waddleWing",
  PEACH_PARASOL = "peachParasol",
  PARACHUTE = "parachute",
  PARAFOIL = "parafoil",
  FLOWER_GLIDER = "flowerGlider",
  BOWSER_KITE = "bowserKite",
  PLANE_GLIDER = "planeGlider",
  MKTV_PARAFOIL = "mktvParafoil",
  GOLD_GLIDER = "goldGlider",
  HYLIAN_KITE = "hylianKite",
  PARAGLIDER = "paraglider",
  PAPER_GLIDER = "paperGlider",
}
