export enum TireName {
  STANDARD = "standard",
  MONSTER = "monster",
  ROLLER = "roller",
  SLIM = "slim",
  SLICK = "slick",
  METAL = "metal",
  BUTTON = "button",
  OFF_ROAD = "offRoad",
  SPONGE = "sponge",
  WOOD = "wood",
  CUSHION = "cushion",
  BLUE_STANDARD = "blueStandard",
  HOT_MONSTER = "hotMonster",
  AZURE_ROLLER = "azureRoller",
  CRIMSON_SLIM = "crimsonSlim",
  CYBER_SLICK = "cyberSlick",
  RETRO_OFF_ROAD = "retroOffRoad",
  GOLD_TIRES = "goldTires",
  GLA_TIRES = "glaTires",
  TRIFORCE_TIRES = "triforceTires",
  ANCIENT_TIRES = "ancientTires",
  LEAF_TIRES = "leafTires",
}
